### PR TITLE
Lily_Su_Weekly Routine Check-in Unit-1-Sprint-3

### PR DESCRIPTION
**Pull request by LilySu**
Weekly Routine Check-in Unit-1-Sprint-3

### CODE REVIEW

**Comment by Dpgofast** [comment]
Good job making your portfolio website! Keep adding to it to have a polished and powerful piece of personalized advertisement! Look into how to change font and colors in order to make your template even more unique.

**Comment by Dpgofast** [comment]
Great work replicating a visualization! The libraries profiled today are quite powerful and will be very useful in your data visualization project. Keep up the good work!

**Comment by Dpgofast** [comment]
Work with a visualization and try to recreate it, Starting simple is the best way to go. Recreating a bar chart or line graph and adhering to the styles of someone like 538 will enable you to dig deep into the abilities of plotting libraries. Keep up the good work!

**Comment by LilySu** [comment]
Lily Su Week 4 Pull Request

**Pull request closed without merging**
